// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFilesToWorkspace(arg1) {
  return window['go']['main']['App']['AddFilesToWorkspace'](arg1);
}

export function AddServer(arg1) {
  return window['go']['main']['App']['AddServer'](arg1);
}

export function AnalyzeFile(arg1) {
  return window['go']['main']['App']['AnalyzeFile'](arg1);
}

export function CancelRequest(arg1) {
  return window['go']['main']['App']['CancelRequest'](arg1);
}

export function CloseAllSession() {
  return window['go']['main']['App']['CloseAllSession']();
}

export function CloseSession(arg1) {
  return window['go']['main']['App']['CloseSession'](arg1);
}

export function ConnectSession(arg1) {
  return window['go']['main']['App']['ConnectSession'](arg1);
}

export function CreateWorkspace(arg1) {
  return window['go']['main']['App']['CreateWorkspace'](arg1);
}

export function DeleteServer(arg1) {
  return window['go']['main']['App']['DeleteServer'](arg1);
}

export function DeleteWorkspace(arg1) {
  return window['go']['main']['App']['DeleteWorkspace'](arg1);
}

export function GetAllWorkspaces() {
  return window['go']['main']['App']['GetAllWorkspaces']();
}

export function GetListSession() {
  return window['go']['main']['App']['GetListSession']();
}

export function GetLocalDrives() {
  return window['go']['main']['App']['GetLocalDrives']();
}

export function GetLocalRootPath() {
  return window['go']['main']['App']['GetLocalRootPath']();
}

export function GetLocalUserHomeDir() {
  return window['go']['main']['App']['GetLocalUserHomeDir']();
}

export function GetRemoteListFiles(arg1, arg2) {
  return window['go']['main']['App']['GetRemoteListFiles'](arg1, arg2);
}

export function GetServerById(arg1) {
  return window['go']['main']['App']['GetServerById'](arg1);
}

export function GetSession(arg1) {
  return window['go']['main']['App']['GetSession'](arg1);
}

export function GetWorkspace(arg1) {
  return window['go']['main']['App']['GetWorkspace'](arg1);
}

export function ListLocalFiles(arg1) {
  return window['go']['main']['App']['ListLocalFiles'](arg1);
}

export function ListServers() {
  return window['go']['main']['App']['ListServers']();
}

export function RemoveFileFromWorkspace(arg1) {
  return window['go']['main']['App']['RemoveFileFromWorkspace'](arg1);
}

export function TestConnection(arg1, arg2) {
  return window['go']['main']['App']['TestConnection'](arg1, arg2);
}

export function UpdateServer(arg1) {
  return window['go']['main']['App']['UpdateServer'](arg1);
}

export function UpdateWorkspace(arg1) {
  return window['go']['main']['App']['UpdateWorkspace'](arg1);
}
