// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';

export function AddServer(arg1:dto.ServerCreateRequest):Promise<dto.ServerResponse>;

export function CancelRequest(arg1:string):Promise<void>;

export function CloseAllSession():Promise<void>;

export function CloseSession(arg1:string):Promise<void>;

export function ConnectSession(arg1:string):Promise<string>;

export function DeleteServer(arg1:string):Promise<void>;

export function GetListSession():Promise<Array<dto.SessionManagerDto>>;

export function GetLocalDrives():Promise<Array<dto.DriveInfo>>;

export function GetLocalRootPath():Promise<string>;

export function GetLocalUserHomeDir():Promise<string>;

export function GetRemoteListFiles(arg1:string,arg2:string):Promise<Array<dto.FileInfo>>;

export function GetServerById(arg1:string):Promise<dto.ServerResponse>;

export function GetSession(arg1:string):Promise<dto.SessionManagerDto>;

export function ListLocalFiles(arg1:string):Promise<Array<dto.FileInfo>>;

export function ListServers():Promise<Array<dto.ServerResponse>>;

export function TestConnection(arg1:string,arg2:dto.ServerCreateRequest):Promise<void>;

export function UpdateServer(arg1:dto.ServerUpdateRequest):Promise<void>;
