// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddServer(arg1) {
  return window['go']['main']['App']['AddServer'](arg1);
}

export function CancelRequest(arg1) {
  return window['go']['main']['App']['CancelRequest'](arg1);
}

export function CloseAllSession() {
  return window['go']['main']['App']['CloseAllSession']();
}

export function CloseSession(arg1) {
  return window['go']['main']['App']['CloseSession'](arg1);
}

export function ConnectSession(arg1) {
  return window['go']['main']['App']['ConnectSession'](arg1);
}

export function DeleteServer(arg1) {
  return window['go']['main']['App']['DeleteServer'](arg1);
}

export function GetListFiles(arg1, arg2) {
  return window['go']['main']['App']['GetListFiles'](arg1, arg2);
}

export function GetServerById(arg1) {
  return window['go']['main']['App']['GetServerById'](arg1);
}

export function GetSession(arg1) {
  return window['go']['main']['App']['GetSession'](arg1);
}

export function GetUserHomeDir() {
  return window['go']['main']['App']['GetUserHomeDir']();
}

export function ListFiles(arg1) {
  return window['go']['main']['App']['ListFiles'](arg1);
}

export function ListServers() {
  return window['go']['main']['App']['ListServers']();
}

export function TestConnection(arg1, arg2) {
  return window['go']['main']['App']['TestConnection'](arg1, arg2);
}

export function UpdateServer(arg1) {
  return window['go']['main']['App']['UpdateServer'](arg1);
}
