// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';

export function AddServer(arg1:dto.ServerCreateRequest):Promise<dto.ServerResponse>;

export function DeleteServer(arg1:string):Promise<void>;

export function GetServerById(arg1:string):Promise<dto.ServerResponse>;

export function ListServers():Promise<Array<dto.ServerResponse>>;

export function UpdateServer(arg1:dto.ServerUpdateRequest):Promise<void>;
